### ISSUE TITLE
Among us don't work

### ISSUE THREAD

**Issue by e-lunev** [RusNor/StartWine-Launcher#3]
When I launch among au, it throws me to the authorization window, but when I click confirm that my system cannot open the URI

imgs

https://ibb.co/rmg4QsH
https://ibb.co/PgW193m

**Comment by Lintech-1** [comment]
not much I can suggest, but try slipping the launcher url, although you can go to the startwine discord server for details and to solve the problem https://discord.gg/jjY3auVdfm
