### ISSUE TITLE
new idea : can add StartWine-Launcher.APPIMAGE ?

### ISSUE THREAD

**Issue by n0bzeR** [RusNor/StartWine-Launcher#34]
Just want see portable version, with all depencies !
possibly add it??
APPIMAGE really good idea! if you add it - its cool!
 1-4gb for .appimage - NOT PROBLEM

**Comment by Lintech-1** [comment]
StartWine already has its own built-in container and no dependencies are needed, except for displaying the progress bar when installing sw https://github.com/RusNor/StartWine-Launcher/issues/34
