### ISSUE TITLE
issue on fedora distrubition

### ISSUE THREAD

**Issue by FELLUFE** [RusNor/StartWine-Launcher#35]
i cant install startwine on fedora, just there is no any instructions how to install wine on fedora, and informatin in this site doesnt work on fedora

**Comment by Lintech-1** [comment]
If you have this error, then install aria2 to solve the problem
`sudo dnf install aria2`

![image](https://github.com/RusNor/StartWine-Launcher/assets/81373196/4de83ef6-9eba-4845-ab27-a1470fcf6a66)
