### ISSUE TITLE
Error start on arch linux

### ISSUE THREAD

**Issue by BlackSoulHub** [RusNor/StartWine-Launcher#36]
Result of `startwine`:
```
Traceback (most recent call last):
  File "/.local/share/StartWine/data/scripts/sw_menu.py", line 103, in <module>
    import gi
  File "/.local/lib/python3.12/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: libffi.so.8: cannot open shared object file: No such file or directory
```

**Comment by BlackSoulHub** [comment]
> What Linux distribution are you running?

Arch

**Comment by Lintech-1** [comment]
These packages may have been missing, enter the command in terminal
`sudo pacman -Syu libffi lib32-libffi`

**Comment by BlackSoulHub** [comment]
> These packages may have been missing, enter the command in terminal `sudo pacman -Syu libffi lib32-libffi`

Not working. Result after command:
```
Traceback (most recent call last):
  File "/.local/share/StartWine/data/scripts/sw_menu.py", line 103, in <module>
    import gi
  File "/.local/lib/python3.12/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: libffi.so.8: cannot open shared object file: No such file or directory
```

**Comment by Lintech-1** [comment]
Have you updated your system to the latest version of packages? and enter the command 
`find . -name libffi.so.8`

**Comment by Lintech-1** [comment]
As far as I've read, this error is usually due to either the libffi compilation itself, or some other dependency interfering with the libffi library.

**Comment by BlackSoulHub** [comment]
> Have you updated your system to the latest version of packages? and enter the command `find . -name libffi.so.8`

I didn't found it in home folder (`find . -name libffi.so.8`)

But i found it in root folder (`find / -name libffi.so.8`):
`/usr/lib/libffi.so.8`

I try to copy lib to `/.local/lib/python3.12/site-packages/gi`, but it's not working

**Comment by Lintech-1** [comment]
Hmm, something I don't see lib32 path to the library is ok, try installing these packages. Probably only recently installed the system, and knowing how clean Arch can be this might help you. I myself have these packages installed on my system

`sudo pacman -Syu zstd imagemagick vulkan-tools xdg-user-dirs htop vte3 python-gobject python-cairo python-opengl python-pillow python-numpy python-six`

I also found that I have files with this library displayed from this version, maybe you have an older version? (although that's bullshit, but what the hell :))) )
![image](https://github.com/RusNor/StartWine-Launcher/assets/81373196/4978af87-d232-4d3d-9245-0f44279c20ed)

**Comment by BlackSoulHub** [comment]
I have `find / -name libffi.so.8` output:
```
/usr/lib/libffi.so.8
/usr/lib32/libffi.so.8
```

But i have same error

**Comment by Lintech-1** [comment]
Then let's try downgrading the package versions to a previous version 

https://archive.archlinux.org/repos/2024/02/19/core/os/x86_64/libffi-3.4.5-1-x86_64.pkg.tar.zst
https://archive.archlinux.org/repos/2024/02/19/multilib/os/x86_64/lib32-libffi-3.4.5-1-x86_64.pkg.tar.zst

> [!TIP] 
> Where the asterisk is, write the name of the downloaded package

`sudo pacman -U ./*-x86_x64.pkg.tar.zst`

**Comment by BlackSoulHub** [comment]
> Then let's try downgrading the package versions to a previous version

This doesn't sound right. Error message: `cannot open shared object file: No such file or directory`.
It looks like it can't find the file, not some function in the library.

But now I'm very tired of this Python error. I think we can close this issue.
Thanks for trying to help! :+1:

**Comment by Lintech-1** [comment]
I understand, we are not gurus in python libraries helped with what I could. I myself by the way use such a system as CachyOS, there from the box everything is already configured and you can customize the system for yourself :) just I myself am tired of the eternal same Arch Linux configuration. 
![image](https://github.com/RusNor/StartWine-Launcher/assets/81373196/a8be1862-cf73-473e-aa98-de061193b1f6)
