### ISSUE TITLE
"bwrap: setting up uid map: Permission denied" on ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by aron1cx** [RusNor/StartWine-Launcher#37]
**Hardware information**
**Model:** Dell Inc. Inspiron 5559
**Memory:** 16,0 Гиб
**Processor:** Intel® Core™ i7-6500U x 4
**Graphics:** Intel® HD Graphics 520 (SKL GT2)
**Graphics 1:** HAINAN 10

**Programme information**
**Firmware version:** 1.9.0
**OS name:** Ubuntu Oracular Oriole (development branch)
**OS type:** 64-бит
**GNOME version:** 46
**Window interface:** Wayland
**Kernel version:** Linux 6.8.0-35-generic

```
atm@root:~/Downloads$ ./StartWine_v404
######################################################################### 100.0%
Download complete succsessfully.
[ INFO ][2024.06.26 18:25:24]: Found RunImage internal config: sw_runtime.rcfg 
[ INFO ][2024.06.26 18:25:24]: Remounting RunImage with squashfuse... 
[ WARNING ][2024.06.26 18:25:24]: Host '/etc/hosts' is unshared! 
[ WARNING ][2024.06.26 18:25:24]: Hostname are unshared! 
bwrap: setting up uid map: Permission denied
[ INFO ][2024.06.26 18:25:24]: Found RunImage internal config: sw_runtime.rcfg 
[ INFO ][2024.06.26 18:25:24]: Remounting RunImage with squashfuse... 
[ WARNING ][2024.06.26 18:25:24]: Host '/etc/hosts' is unshared! 
[ WARNING ][2024.06.26 18:25:24]: Hostname are unshared! 
bwrap: setting up uid map: Permission denied
```

**Comment by Lintech-1** [comment]
Open terminal
```
sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
```
```
sudo tee -a /etc/sysctl.d/98-apparmor-unuserns.conf <<<kernel.apparmor_restrict_unprivileged_userns=0

reinstall StartWine

**Comment by aron1cx** [comment]
> Open terminal
> 
> ```
> sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
> ```
> 
> ```
> sudo tee -a /etc/sysctl.d/98-apparmor-unuserns.conf <<<kernel.apparmor_restrict_unprivileged_userns=0
> ```
> 
> reinstall StartWine

Thank you
