### ISSUE TITLE
Language Settings

### ISSUE THREAD

**Issue by pjduplooy2022** [RusNor/StartWine-Launcher#40]
Hi guys.

Thank you for the awesome project!!.

I would like to know how to apply changing the language from RU to EN?

I found where to change it in the settings, but I cannot apply the change.  Every time I open the software, the interface language is still in RU.  

I am using 405.

Thanks a lot

**Comment by Lintech-1** [comment]
in the `/etc/locale.gen` file, comment out the following line `en_US.UTF-8 UTF-8`, save the file and enter the command to make the changes `locale-gen`

Additionally, I will give you a link to the Arch Wiki on Locale if there is anything you don't understand or if you want to delve more into this topic
[locale](https://wiki.archlinux.org/title/Locale)

**Comment by pjduplooy2022** [comment]
Hi!!

I performed your suggestion, but I still cannot get it to work in EN.  Do I need to remove the install of SW-Launcher, and reinstall?

Here is a snippet of my locale.gen:

# en_PH.UTF-8 UTF-8
# en_SC.UTF-8 UTF-8
# en_SG ISO-8859-1
# en_SG.UTF-8 UTF-8
# en_US ISO-8859-1
# en_US.ISO-8859-15 ISO-8859-15
#en_US.UTF-8 UTF-8
# en_ZA ISO-8859-1
en_ZA.UTF-8 UTF-8
# en_ZM UTF-8
# en_ZW ISO-8859-1
# en_ZW.UTF-8 UTF-8
# eo UTF-8
# eo_US.UTF-8 UTF-8

The only language that is not commented out is en_ZA.UTF-8 UTF-8

**Comment by pjduplooy2022** [comment]
Hi.  

Disregard my previous message.  I found the settings.  I tried every button until I found what ended up to be interface settings.  I was trying to set the language in the set game or app language settings.

Thank you very much.
