### ISSUE TITLE
Configuration and Performance Issue in Ready or Not

### ISSUE THREAD

**Issue by Belgorodski** [RusNor/StartWine-Launcher#43]
## My Configuration:
- **Monitor:** 1920x1080
- **Graphics Card:** RTX 3060
- **Driver Version:** 535.183.01

## Issue Description

Although my monitor has a native resolution of 1920x1080, I use virtual resolution scaling to increase it to 3840x2160. This resolution is then downscaled to Full HD, which slightly enhances the image quality.

Upon launching the game *Ready or Not*, I encountered a severe issue: whenever the game is in "windowed focus," the performance immediately drops to 0 FPS, and the GPU load plummets.

The strangest part is that the game continues to run, and the performance can be restored simply by switching to "overview mode" or moving to another workspace, which causes the FPS to return to high levels.

[Video Demonstration](https://drive.google.com/file/d/1rkxZtZrSpFYaEi_iUfzUt6AH-jdxv7BP/view?usp=sharing)

I didn’t record or demonstrate this issue at lower resolutions, but I want to emphasize that this problem does not occur with virtual resolutions below UHD, such as 2560x1440, or at the native 1920x1080 resolution.

**Comment by Belgorodski** [comment]
It turned out to be easier to accomplish my task: select Wayland, install PortProton, and then use it with Gamescope, after first installing Gamescope.

**Comment by Lintech-1** [comment]
Я уже хотел написать что проблема может быть на стороне игры или рабочего окружения Gnome, но раз вы для себя нашли такое решение, ладно
